### ISSUE TITLE
Aspect-ratio

### ISSUE THREAD

**Issue by Skadefryd** [warp-ds/drive#116]
https://warp-ds.github.io/css-docs/aspect-ratio

.aspect-ratio 
.aspect-square
.aspect-video

These guys are generating padding-bottom: undefined

<img width="1098" alt="image" src="https://github.com/warp-ds/drive/assets/462825/030e2a35-5364-4e0a-9d51-2e087cfdff56">

**Comment by siljec** [comment]
Made a ticket in Jira: https://nmp-jira.atlassian.net/browse/WARP-125

**Comment by BalbinaK** [comment]
The reason behind this is that we only have rules for `aspect-[fraction]`, like `aspect-1/1` `aspect-4/3` , and the rule takes whatever comes after `aspect-`, runs a handler to translate the fraction to a percentage value, and then apply that as value of `padding-bottom` property. If the class ends with anything other than a fraction, we’ll get undefined. Looking at [Tailwindcss](https://tailwindcss.com/docs/aspect-ratio#class-reference) I assume that `aspect-video` and `aspect-square` should be shortcuts to `aspect-1/1` and `aspect-16/9` respectively.
