### ISSUE TITLE
Border

### ISSUE THREAD

**Issue by Skadefryd** [warp-ds/drive#117]
border-x, and border-y not working.  

Ment to do the same as border-x-1, and border-y-1, but should be there for consistency. 

https://warp-ds.github.io/css-docs/border-width

**Comment by BalbinaK** [comment]
@AnnaRybkina do you know if this issue can be closed?

**Comment by AnnaRybkina** [comment]
> @AnnaRybkina do you know if this issue can be closed?

I think we need to add those new to the docs and then we can close it. I'll add them now
